version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: blog-db
    ports:
      - "5400:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - db.env
    networks:
      blog-network:


  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: server
    container_name: blog-server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    env_file:
      - ./server/server.env
    restart: always
    depends_on:
      - db
    networks:
      - blog-network

volumes:
  postgres-data:


networks:
  blog-network:
    name: blog-network
    driver: bridge
